name: ola_ism330dhcx_samm10q_decoder
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - scipy
  - pytest
  - loguru
  - pylint
  - ruff
  - flake8
  - gnuplot
  - matplotlib
  - click
  - pip
  - pip:
    - complexipy
    - gnuplotlib
